spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: micro-service-springcloud-config-hacker-dev

---

spring:
  profiles: test
  application:
    name: micro-service-springcloud-config-hacker-test